- name: Handle k3s_flannel_iface
  ansible.builtin.set_fact:
    k3s_installer_opts: "{{ k3s_installer_opts }} --flannel-iface={{ k3s_flannel_iface }}"

- name: Display k3s_installer_opts
  debug:
    msg: "k3s_installer_opts: {{ k3s_installer_opts }}"
