
- name: "Download output/kubeconfig.yml from /etc/rancher/k3s/k3s.yaml (KUBECONFIG)"
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ k3s_output_dir }}/kubeconfig.yml"
    flat: yes

- name: "Replace 127.0.0.1 by {{ ansible_ssh_host }} in output/kubeconfig.yml"
  replace:
    path: "{{ k3s_output_dir }}/kubeconfig.yml"
    regexp: '127.0.0.1'
    replace: "{{ ansible_ssh_host }}"
  become: false
  delegate_to: localhost

