- name: "Fetch output/node-token from /var/lib/rancher/k3s/server/node-token to allow joining from agent"
  fetch:
    src: /var/lib/rancher/k3s/server/node-token
    dest: "{{ k3s_output_dir }}/"
    flat: yes
