# server or agent
k3s_mode: server

# output directory for kubeconfig.yml and node-token
k3s_output_dir: "{{ playbook_dir|dirname }}/output"

# required for agent
k3s_url: ~
k3s_token: ~

# command line opts (ex : '--disable traefik --write-kubeconfig-mode 644 --flannel-iface=enp0s8')
k3s_installer_opts: ''
# ex : 'v1.28'
k3s_channel: 'stable'

k3s_extra_opts: []

# Allows to use a Docker Hub mirror
# see https://docs.docker.com/registry/recipes/mirror/
# ex : https://docker-mirror.quadtreeworld.net/ (IP filtered)
k3s_docker_mirror: ~
